// Self-contained HTML compliance report (inline CSS + a little vanilla JS, no deps).
// Modelled on tieline's report: a health ring, summary cards, and per-pack control
// tables with each rule's verdict, the legal standard, and file-level evidence.

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

const shortFile = (f) => {
  const p = String(f).split("/");
  return p.length > 2 ? p.slice(-2).join("/") : String(f);
};
const locCell = (file, line) =>
  `<td class="loc" title="${esc(file)}${line ? ":" + line : ""}">${esc(shortFile(file))}${line ? ":" + line : ""}</td>`;

export function reportHtml(result, meta = {}) {
  const { findings = [], totals = {}, score = 100, meta: rmeta = {} } = result;

  const byPack = new Map();
  for (const f of findings) {
    if (!byPack.has(f.packId)) byPack.set(f.packId, []);
    byPack.get(f.packId).push(f);
  }

  const packSections = [...byPack.values()].map((rows) => packTable(rows)).join("\n");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>bouncer · compliance report</title>
<style>${CSS}</style></head>
<body>
<header class="hero">
  <div class="hero-inner">
    <div class="brand"><span class="logo">⛨</span> bouncer<span class="sub">compliance report</span></div>
    <div class="meta">
      <span>${esc(rmeta.adapter || "adapter")} · ${esc(String(rmeta.filesScanned ?? 0))} files</span>
      ${meta.generatedAt ? `<span class="dim">${esc(meta.generatedAt)}</span>` : ""}
    </div>
  </div>
  <div class="ring" style="--p:${score}">
    <svg viewBox="0 0 120 120"><circle class="track" cx="60" cy="60" r="52"/><circle class="value ${score >= 90 ? "ok" : score >= 70 ? "warn" : "bad"}" cx="60" cy="60" r="52"/></svg>
    <div class="ring-label"><strong>${score}%</strong><span>controls present</span></div>
  </div>
</header>

<main>
  <section class="cards">
    ${card("pass", totals.pass || 0, "ok", "required control found")}
    ${card("fail", totals.fail || 0, "bad", "surface exists, control missing")}
    ${card("unknown", totals.unknown || 0, "warn", "surface not located — can't determine")}
  </section>

  <p class="disclaimer">bouncer checks that the controls a regulation requires are present in code. It is an engineering aid, <strong>not legal advice</strong> and not a substitute for a compliance/DPO review.</p>

  ${packSections}
</main>

<footer>Generated by <strong>bouncer</strong> · static compliance-controls checker</footer>
<script>${JS}</script>
</body></html>`;
}

function card(label, value, kind, sub) {
  return `<div class="cardx ${kind}"><div class="num">${value}</div><div class="lab">${esc(label)}</div><div class="csub">${esc(sub)}</div></div>`;
}

function packTable(rows) {
  const head = rows[0];
  const ordered = [...rows].sort((a, b) => order(a.status) - order(b.status));
  const body = ordered
    .map((f) => {
      const evidence =
        f.status === "pass" && f.hits[0]
          ? locCell(f.hits[0].file, f.hits[0].line)
          : f.status === "fail" && f.hits[0]
            ? locCell(f.hits[0].file, f.hits[0].line)
            : `<td class="loc dim">${f.status === "unknown" ? "not located" : "—"}</td>`;
      const detail =
        f.status === "fail"
          ? `<div class="sub">${esc(f.intent || "")}</div><div class="fix">Fix: ${esc(f.fix || "")}</div>`
          : f.status === "unknown"
            ? `<div class="sub dim">surface not found in this repo — can't determine</div>`
            : "";
      return `<tr data-status="${f.status}" data-text="${esc(f.ruleId + " " + (f.standard || ""))}">
        <td class="verdict"><span class="pill ${f.status}">${esc(f.status)}</span></td>
        <td class="sev ${esc(f.severity)}">${esc(f.severity)}</td>
        <td class="rule"><span class="rid">${esc(f.ruleId)}</span><div class="std">${esc(f.standard || "")}</div>${detail}</td>
        ${evidence}
      </tr>`;
    })
    .join("\n");

  return `<section class="panel">
    <h2>${esc(head.packTitle)}</h2>
    <p class="hint">${esc(head.authority || "")} &nbsp;·&nbsp; <span class="k ok">●</span> pass · <span class="k bad">●</span> fail · <span class="k warn">●</span> unknown</p>
    <table class="grid">
      <thead><tr><th>Verdict</th><th>Severity</th><th>Control / standard</th><th>Evidence</th></tr></thead>
      <tbody>${body}</tbody>
    </table>
  </section>`;
}

function order(status) {
  return status === "fail" ? 0 : status === "unknown" ? 1 : 2;
}

const CSS = `
:root{--bg:#0d1117;--panel:#161b22;--line:#21262d;--ink:#e6edf3;--dim:#8b949e;--ok:#2ea043;--bad:#f85149;--warn:#d29922;--mute:#6e7681}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
.hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px 32px;background:linear-gradient(135deg,#161b22,#0d1117);border-bottom:1px solid var(--line)}
.brand{font-size:22px;font-weight:700;letter-spacing:.3px}
.brand .logo{color:#58a6ff;margin-right:6px}
.brand .sub{font-size:13px;font-weight:500;color:var(--dim);margin-left:10px}
.meta{margin-top:6px;color:var(--dim);font-size:13px;display:flex;gap:14px}
.meta .dim{color:var(--mute)}
.ring{position:relative;width:120px;height:120px;flex:none}
.ring svg{transform:rotate(-90deg)}
.ring .track{fill:none;stroke:var(--line);stroke-width:10}
.ring .value{fill:none;stroke-width:10;stroke-linecap:round;stroke-dasharray:calc(var(--p)*3.27) 327}
.ring .value.ok{stroke:var(--ok)}.ring .value.warn{stroke:var(--warn)}.ring .value.bad{stroke:var(--bad)}
.ring-label{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}
.ring-label strong{font-size:24px}.ring-label span{font-size:11px;color:var(--dim)}
main{max-width:1040px;margin:0 auto;padding:28px 32px}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}
.cardx{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px 18px}
.cardx .num{font-size:30px;font-weight:700}
.cardx .lab{text-transform:uppercase;letter-spacing:.6px;font-size:12px;color:var(--dim)}
.cardx .csub{font-size:12px;color:var(--mute);margin-top:4px}
.cardx.ok .num{color:var(--ok)}.cardx.bad .num{color:var(--bad)}.cardx.warn .num{color:var(--warn)}
.disclaimer{background:#1c2128;border:1px solid var(--line);border-radius:8px;padding:10px 14px;color:var(--dim);font-size:12.5px}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:18px 20px;margin-top:18px}
.panel h2{margin:0 0 2px;font-size:16px}
.hint{color:var(--dim);font-size:12.5px;margin:0 0 12px}
.k{font-size:10px;vertical-align:middle}.k.ok{color:var(--ok)}.k.bad{color:var(--bad)}.k.warn{color:var(--warn)}
table.grid{width:100%;border-collapse:collapse;font-size:13px}
.grid th{text-align:left;color:var(--dim);font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.5px;padding:6px 10px;border-bottom:1px solid var(--line)}
.grid td{padding:10px;border-bottom:1px solid var(--line);vertical-align:top}
.pill{display:inline-block;padding:2px 9px;border-radius:999px;font-size:11px;font-weight:700;text-transform:uppercase}
.pill.pass{background:rgba(46,160,67,.15);color:var(--ok)}
.pill.fail{background:rgba(248,81,73,.15);color:var(--bad)}
.pill.unknown{background:rgba(210,153,34,.15);color:var(--warn)}
.sev{font-size:12px;text-transform:capitalize;color:var(--dim)}
.sev.high{color:var(--bad)}.sev.medium{color:var(--warn)}
.rule .rid{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px}
.rule .std{color:var(--dim);font-size:12px;margin-top:2px}
.rule .sub{margin-top:6px;font-size:12.5px}
.rule .fix{margin-top:3px;font-size:12px;color:#7ee787}
.loc{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#79c0ff;white-space:nowrap}
.dim{color:var(--mute)}
footer{max-width:1040px;margin:0 auto;padding:20px 32px 40px;color:var(--mute);font-size:12px}
`;

const JS = `
// no-op placeholder for future filtering; report is fully static.
document.querySelectorAll('.pill').forEach(function(p){});
`;
